### ISSUE TITLE
Error in loadNamespace(x) : there is no package called ‘ca’

### ISSUE THREAD

**Issue by BigMacQueen** [corybrunson/ordr.extra#5]
I get this error when attempting to use the line:

(MP_JCA <- ordinate(MP, ca::mjca, lambda = "JCA"))

I have installed ordr.extra_0.0.0.9000.tar.gz'

I am running the latest Rstudio

**Comment by corybrunson** [comment]
Hi @BigMacQueen, thanks for bringing this up. This is something i think worth explaining in the README, so i'll leave this issue open as a reminder to do so.

{ordr.extra} provides methods for modeling functions in several other packages, but it does not strongly depend on those packages. The reason is so that users who have one of these packages, like {ca}, installed can use it with {ordr.extra} without having to have all of the others installed as well. But it does mean that the user must manually install any modeling packages they want to use.

{ca} is on CRAN, so you should be able to install it as follows:

```r
install.packages("ca")
```

You should then be able to run the code you tried. Please comment again whether this works and if any other issues arise!
